apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-ipassigner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-ipassigner
    spec:
      containers:
        - name: ipassigner
          image: 163.143.94.199:5000/rollman/ipassigner:0.0.2
          ports:
            - containerPort: 8080
